- id: js-beautify
  name: js-beautify
  entry: js-beautify
  language: node
  files: \.js$
  args: []
  additional_dependencies: ['js-beautify@1.14.6']
  minimum_pre_commit_version: 3.0.0
  description: "Runs `js-beautify`"
